# DO NOT change the order of features EVER
- name: inbound_emails
  enabled: true
- name: channel_email
  enabled: true
- name: channel_facebook
  enabled: true
- name: channel_twitter
  enabled: true
- name: ip_lookup
  enabled: false
- name: disable_branding
  enabled: false
  premium:  true
- name: email_continuity_on_api_channel
  enabled: false
- name: help_center
  enabled: true
- name: agent_bots
  enabled: false
- name: macros
  enabled: true
- name: agent_management
  enabled: true
- name: team_management
  enabled: true
- name: inbox_management
  enabled: true
- name: labels
  enabled: true
- name: custom_attributes
  enabled: true
- name: automations
  enabled: true
- name: canned_responses
  enabled: true
- name: integrations
  enabled: true
- name: voice_recorder
  enabled: true
- name: mobile_v2
  enabled: true
- name: channel_website
  enabled: true
- name: campaigns
  enabled: true
- name: reports
  enabled: true
- name: crm
  enabled: true
- name: custom_reply_email
  enabled: false
- name: custom_reply_domain
  enabled: false
- name: audit_logs
  enabled: false
- name: response_bot
  enabled: false
- name: message_reply_to
  enabled: true
- name: insert_article_in_reply
  enabled: false
- name: inbox_view
  enabled: false
- name: read_message
  enabled: true
- name: hide_filters_for_agent
  enabled: false
- name: hide_all_chats_for_agent
  enabled: false
- name: hide_contacts_for_agent
  enabled: false
- name: auto_resolve_conversations
  enabled: true
- name: send_agent_name_in_whatsapp_message
  enabled: true