version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "sony-mathew"
      - "nestordavalos"
      - "subintp"
    default_labels:
      - "dependencies"
      - "ruby"
    version_requirement_updates: "auto"
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_reviewers:
      - "nestordavalos"
    default_labels:
      - "dependencies"
      - "javascript"
    version_requirement_updates: "auto"
